develop
Julwas/Diplom pull request #7
Opened 2023-09-22 19:35 UTC by Julwas

2023-10-02 06:28 UTC, wildpioneer requested changes

2023-10-02 06:28 UTC, wildpioneer commented on src/test/java/models/Project.java
> +@Getter
Тут надо прям все аннотации Lombok???
И @Data, и @Getter и  @Builder в одном месте???

2023-10-02 06:28 UTC, wildpioneer commented on src/test/java/models/User.java
> +    @SerializedName(value = "id")
Форматирование - пустые строки между блоками

2023-10-02 06:28 UTC, wildpioneer commented on src/test/java/pages/MyProjectsPage.java
> +        getDownloadFileButton().sendKeys(pathToFile.substring(1));
У меня не работает - хотя пример, как должно быть, я приводил уже 3 раза как

2023-10-02 06:28 UTC, wildpioneer commented on src/test/java/tests/api/ApiGetAllProjectsTest.java
> +       Assert.assertEquals(actualProjects.get(11), expectedProject);
А если добавиться еще проектов - тогда не 11 будет???

2023-10-02 06:28 UTC, wildpioneer commented on src/test/java/tests/api/ApiGetProjectTest.java
> +    @Test
Форматирование

2023-10-02 06:28 UTC, wildpioneer commented on src/test/java/tests/api/ApiGetProjectTest.java
> +        Response response = given()
Почему все эти вызовы находятся в тесте а не в адаптере?

2023-10-02 06:28 UTC, wildpioneer commented on src/test/java/tests/gui/UITests.java
>          SelenideElement elementText = $
НИкаких использований селекторов в самом тесте быть не должно

2023-10-02 06:28 UTC, wildpioneer commented on src/test/java/tests/gui/UITests.java
>          open(ReadProperties.getUrl());
В каждом тесте открывается начальная страница????? Это дубликаты кода - исправить

2023-10-02 06:28 UTC, wildpioneer commented on src/test/java/tests/gui/UITests.java
>      @Description("Checking the input field for boundary values.")
Форматирование

2023-10-04 08:12 UTC, Julwas commented on src/test/java/models/Project.java
> +@Getter
исправлено

2023-10-04 08:12 UTC, Julwas commented
можно проверять

2023-10-04 09:21 UTC, wildpioneer commented on src/test/java/models/Project.java
> +@Getter
:) Не угадали 
Надо было @Getter @Builder оставить

2023-10-04 09:37 UTC, merged